In [1]:
import numpy as np

In [20]:
class Warnsdorff:
    def __init__(self,n):
        self.n = n
        self.maze = np.array([0 for i in range(n**2)]).reshape(n,n)
        self.count=0
        self.moves = []
    
    def possible_moves(self,x,y):
        x_comb = [2,-2]
        y_comb = [1,-1]
        moves = [(x+i,y+j) for i in x_comb for j in y_comb if (x+i<self.n and x+i>-1 and y+j<self.n and y+j>-1)]+[(x+j,y+i) for i in x_comb for j in y_comb if (x+j<self.n and x+j>-1 and y+i<self.n and y+i>-1)]
        moves = [(i) for i in moves if self.maze[i]==0]        
        return moves
    
    def sort_moves(self,x,y):
        self.moves = self.possible_moves(x,y)
        move_count = {}
        for move in self.moves:
            move_count[move] = len(self.possible_moves(move[0],move[1]))
        self.moves.sort(key=lambda x:move_count[x])
        return self.moves
    
    def solve(self,x,y):
        self.count+=1
        self.maze[x,y]=self.count
        print(self.maze)
        print("-"*10,x,y,"-"*12)
        moves = self.possible_moves(x,y)
        moves = self.sort_moves(x,y)
    
        if len(moves)==0:
            if self.count==self.n*self.n:
                return True
            else:
                return False
        else:
            for move in moves:
                if self.solve(move[0],move[1]):
                    return True
                else:
                    self.maze[move[0],move[1]]=0
                    self.count-=1

        return False
        

In [21]:
w = Warnsdorff(8)

In [22]:
w.solve(0,0)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
---------- 0 0 ------------
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
---------- 2 1 ------------
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
---------- 4 0 ------------
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
---------- 6 1 ------------
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0]]
---------- 7 3 ------------
[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0]


True